steps:
  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','greeting']
    env: ['PROJECT_ROOT=fullcycle-7-desafio-deploy-continuo', 'GOPATH=.']

  - id: 'Building image from Dockerfile'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA','-f','Dockerfile','.']

  - id: 'Pushing image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA']

  - id: 'Adjusting deployment file k8s'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#image-go-hpa#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g' deployment.yaml > deployment-new.yaml;
        cat deployment-new.yaml;
  - id: 'Deploying k8s'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment-new.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=fullcycle7'